apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment
  labels:
    app: nginx
spec:
  replicas: 3
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: nginx
        image: 874049927853.dkr.ecr.ap-south-1.amazonaws.com/node-pipeline:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 80
